### ISSUE TITLE
Non-member dummy issue

### ISSUE THREAD

**Issue by ntutland** [QF-Error-Tracking/QFVD3.1.1#2]
**Describe the bug**
Let's see if I can submit a bug report

**To Reproduce**
Seems to be working

**Desktop (please complete the following information):**
 - QF Version [e.g. QFVD3.1.1]
 - OS: [e.g. Ubuntu, Mac]
 - Hardware SPECs [If applicable]

**Screenshots**

**Comment by zacharycope0** [comment]
Thanks Niko
