### ISSUE TITLE
QF Topo crashes with very little terrain (<50m) early in runs (<100s) [BIA_SanCarlos Runs]

### ISSUE THREAD

**Issue by drosales95** [QF-Error-Tracking/QFVD3.1.1#6]
**Describe the bug**
Not much to say other than the run very reliably crashes when topo is used before the 100s mark. 

Will be available for helping to debug/test where this is coming from. It's not related to RAM or
Ubuntu version as far as I know since it also crashed on my workstation (256 GB RAM /  Ubuntu 16)
but could likely be due to the WSL. Have not run it on debug mode.

**To Reproduce**
Email me for the files since the fuel files are pretty  large
Email: dgiron@talltimbers.org

**Desktop (please complete the following information):**
 - QF Version QFVD3.1.1
 - OS: Ubuntu 18.04 through WSL (Windows 10)
 - Hardware SPECs : 16 GB RAM

**Screenshots**

**Comment by drosales95** [comment]
Here is a link to the run:

https://drive.google.com/file/d/1pl--VVep6wpWrSrX9pFzt4GKuCBHoKdN/view?usp=sharing

**Comment by zacharycope0** [comment]
My bad @drosales95. I'll do a better job monitoring issues in the new [QFVD5 repo](https://github.com/QF-Error-Tracking/QFVD5). If you know who you want to look at a particular problem you can assign David or Sara and they will be notified.

![image](https://user-images.githubusercontent.com/43671145/195165316-bcb17987-dfa5-4e70-a434-f1cd6c1ceda3.png)
